### ISSUE TITLE
Context length error

### ISSUE THREAD

**Issue by mherrmann** [brave/pull-merge#95]
https://github.com/brave/omaha/pull/71#issuecomment-2008587370

```
[[puLL-Merge](https://github.com/brave/pull-merge)] - [actions/checkout@v3.1.0..v3.6.0](https://github.com/actions/checkout/compare/v3.1.0..v3.6.0.diff)

logError 400 This model's maximum context length is 16385 tokens. However, your messages resulted in 678344 tokens. Please reduce the length of the messages.
```

**Comment by thypon** [comment]
This is controlled [here](https://github.com/brave/pull-merge/blob/main/action.yml#L240), and it's expected to output this error, when the LLM provider is not supporting big enough context
